export const FETCH_ALL_CATEGORY_POSTS_REQUEST = 'app/HOME/FETCH_ALL_CATEGORY_POSTS_REQUEST';
export const FETCH_ALL_CATEGORY_POSTS_SUCCESS = 'app/HOME/FETCH_ALL_CATEGORY_POSTS_SUCCESS';
export const FETCH_ALL_CATEGORY_POSTS_FAILURE = 'app/HOME/FETCH_ALL_CATEGORY_POSTS_FAILURE';
