export const FETCH_POSTS_REQUEST = 'app/HOME/FETCH_POSTS_REQUEST';
export const FETCH_POSTS_SUCCESS = 'app/HOME/FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAILURE = 'app/HOME/FETCH_POSTS_FAILURE';